import { useEffect, useState } from 'react';
import type { Language } from '../app/types';
import { getPlatformInfo, type PlatformInfo } from '../features/platform/desktopClient';
import { Icon } from '../components/Icon';
import { openExternal } from '../features/updates/updateClient';
import chrisStudioLogo from '../assets/chris-studio-logo.png';
import { CHRIS_STUDIO_CONTACT } from '../app/identity';

const copy = (language: Language, en: string, zh: string) => language === 'zh-CN' ? zh : en;
const fallback: PlatformInfo = { appVersion: '2.3.0-alpha.4', os: 'Loading…', arch: 'Loading…', secureStore: 'Loading…', desktopRuntime: true };
export function AboutScreen({ language }: { language: Language }) {
  const [platform, setPlatform] = useState<PlatformInfo>(fallback);
  useEffect(() => { void getPlatformInfo().then(setPlatform); }, []);
  return <main className="modern-page about-modern"><section className="about-modern-hero"><div className="about-logo"><img src={chrisStudioLogo} alt="Chris Studio" /></div><span className="section-kicker">CHRIS STUDIO {platform.appVersion}</span><h1>{copy(language, 'The safety and cost control layer for AI work.', '面向 AI 工作流的安全与成本控制层。')}</h1><p>{copy(language, 'Multi-provider routing, local file processing, token compaction and permission-gated agents in one desktop workspace.', '在一个桌面工作台中整合多模型路由、本地文件处理、Token 压缩与权限受控 Agent。')}</p><div><button className="button primary" onClick={() => void openExternal('https://github.com/Chrisbetheking/chris-studio')}><Icon name="git" />GitHub</button><button className="button secondary" onClick={() => void openExternal('https://github.com/Chrisbetheking/chris-studio/issues')}><Icon name="external" />Issues</button></div><div className="support-contact"><strong>{copy(language, 'Designed and built by Chris', '由 Chris 全程设计与构建')}</strong><span>Email · {CHRIS_STUDIO_CONTACT.email}</span><span>WeChat · {CHRIS_STUDIO_CONTACT.wechat}</span></div></section><section className="about-feature-grid"><article><Icon name="route" /><strong>Provider Mesh</strong><p>{copy(language, 'Cloud, local and compatible APIs with explicit routing.', '云端、本地与兼容接口的明确路由。')}</p></article><article><Icon name="sparkles" /><strong>Token Control</strong><p>{copy(language, 'Compact context locally before provider billing.', '在 Provider 计费前本地压缩上下文。')}</p></article><article><Icon name="fileText" /><strong>Context Pipeline</strong><p>PDF · DOCX · XLSX · OCR · Code</p></article><article><Icon name="bot" /><strong>Agent Studio</strong><p>{copy(language, 'Reusable skills and permission modes.', '可复用 Skills 与权限模式。')}</p></article></section><section className="about-runtime"><div><span>{copy(language, 'Version', '版本')}</span><strong>{platform.appVersion}</strong></div><div><span>{copy(language, 'Platform', '平台')}</span><strong>{platform.os} · {platform.arch}</strong></div><div><span>{copy(language, 'Credential store', '凭证库')}</span><strong>{platform.secureStore}</strong></div><div><span>Runtime</span><strong>{platform.desktopRuntime ? 'React · TypeScript · Tauri' : 'Browser preview'}</strong></div><div><span>License</span><strong>MIT</strong></div></section></main>;
}
