import { useState } from 'react';
import type { AppSettings, Language, ScreenId, ThemeMode } from '../app/types';
import { clearConversations, clearReceipts, clearTokenUsage, exportLocalSettings, loadProviderProfiles, loadSettings, resetApplication, saveSettings, tokenUsageSummary } from '../app/store';
import { deleteProviderSecret } from '../features/platform/desktopClient';
import { Icon } from '../components/Icon';
import { useToast } from '../components/Toast';

const copy = (language: Language, en: string, zh: string) => language === 'zh-CN' ? zh : en;
function Toggle({ checked, onChange, title, detail }: { checked: boolean; onChange: (value: boolean) => void; title: string; detail: string }) { return <label className="toggle-card"><span><strong>{title}</strong><small>{detail}</small></span><span className="switch"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /><span /></span></label>; }

export function SettingsScreen({ language, onSettingsChanged }: { language: Language; onSettingsChanged: (settings: AppSettings) => void }) {
  const [settings, setSettings] = useState<AppSettings>(() => loadSettings());
  const [customTerms, setCustomTerms] = useState(() => settings.customSensitiveTerms.join('\n'));
  const toast = useToast();
  const usage = tokenUsageSummary();
  const update = <K extends keyof AppSettings>(key: K, value: AppSettings[K]) => setSettings((current) => ({ ...current, [key]: value }));
  const save = () => { const next = { ...settings, customSensitiveTerms: customTerms.split(/\r?\n|,/).map((term) => term.trim()).filter(Boolean).slice(0, 100) }; saveSettings(next); setSettings(next); onSettingsChanged(next); toast.show(copy(language, 'Settings saved.', '设置已保存。'), 'success'); };
  const downloadSettings = () => { const blob = new Blob([exportLocalSettings()], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `chris-studio-settings-${new Date().toISOString().slice(0, 10)}.json`; anchor.click(); URL.revokeObjectURL(url); };
  const resetAll = async () => { if (!window.confirm(copy(language, 'Reset all local Chris Studio data and credentials?', '重置全部本地 Chris Studio 数据与凭证吗？'))) return; for (const profile of loadProviderProfiles()) await deleteProviderSecret(profile.id); resetApplication(); window.location.reload(); };
  return <main className="modern-page settings-page-modern">
    <header className="compact-page-header"><div><span className="section-kicker">PREFERENCES</span><h1>{copy(language, 'Workspace settings', '工作台设置')}</h1><p>{copy(language, 'Control token compaction, safety gates, local processors and GitHub updates.', '控制 Token 压缩、安全门禁、本地处理模块与 GitHub 更新。')}</p></div><div className="header-actions"><button className="button primary" onClick={save}><Icon name="check" />{copy(language, 'Save changes', '保存修改')}</button></div></header>
    <div className="settings-sections">
      <section><header><Icon name="layout" /><div><h2>{copy(language, 'Appearance and navigation', '外观与导航')}</h2><p>{copy(language, 'Language, theme and startup destination.', '语言、主题与启动页面。')}</p></div></header><div className="setting-fields"><label><span>{copy(language, 'Language', '语言')}</span><select value={settings.language} onChange={(event) => update('language', event.target.value as Language)}><option value="en">English</option><option value="zh-CN">简体中文</option></select></label><label><span>{copy(language, 'Theme', '主题')}</span><select value={settings.theme} onChange={(event) => update('theme', event.target.value as ThemeMode)}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label><label><span>{copy(language, 'Start screen', '启动页面')}</span><select value={settings.startScreen} onChange={(event) => update('startScreen', event.target.value as ScreenId)}><option value="workspace">Workspace</option><option value="projects">Projects</option><option value="computer">Computer Use</option><option value="skills">Skills</option><option value="connectors">Connectors</option><option value="agents">Agents</option><option value="files">Files</option><option value="providers">Providers</option></select></label></div></section>
      <section><header><Icon name="sparkles" /><div><h2>{copy(language, 'Token control', 'Token 控制')}</h2><p>{copy(language, 'Compact repeated context before billing starts.', '在模型计费前压缩重复上下文。')}</p></div></header><div className="setting-fields"><label><span>{copy(language, 'Optimization mode', '压缩模式')}</span><select value={settings.tokenOptimizationMode} onChange={(event) => update('tokenOptimizationMode', event.target.value as AppSettings['tokenOptimizationMode'])}><option value="off">Off</option><option value="conservative">Conservative</option><option value="balanced">Balanced</option></select></label><label><span>{copy(language, 'Context messages', '上下文消息数')}</span><input type="number" min={2} max={100} value={settings.conversationContextLimit} onChange={(event) => update('conversationContextLimit', Number(event.target.value))} /></label><label><span>{copy(language, 'Per-request token limit', '单次 Token 限制')}</span><input type="number" min={1000} max={1000000} value={settings.maxRequestTokens} onChange={(event) => update('maxRequestTokens', Number(event.target.value))} /></label><label><span>{copy(language, 'Daily token budget', '每日 Token 预算')}</span><input type="number" min={1000} max={10000000} value={settings.dailyTokenBudget} onChange={(event) => update('dailyTokenBudget', Number(event.target.value))} /></label><label><span>{copy(language, 'Timeout (ms)', '超时（毫秒）')}</span><input type="number" min={5000} max={180000} value={settings.requestTimeoutMs} onChange={(event) => update('requestTimeoutMs', Number(event.target.value))} /></label><div className="token-usage-card"><strong>{usage.totalTokens.toLocaleString()}</strong><span>{copy(language, 'tokens used today', '今日已用 Token')}</span><small>{copy(language, `${usage.savedTokens.toLocaleString()} saved by local compaction`, `本地压缩已节约 ${usage.savedTokens.toLocaleString()}`)}</small></div></div></section>
      <section><header><Icon name="shield" /><div><h2>{copy(language, 'Safety policy', '安全策略')}</h2><p>{copy(language, 'These gates apply before provider routing.', '这些门禁会在模型路由之前执行。')}</p></div></header><div className="toggle-grid"><Toggle checked={settings.autoOpenInspector} onChange={(value) => update('autoOpenInspector', value)} title={copy(language, 'Open inspector', '自动打开检查器')} detail={copy(language, 'Show the control rail by default.', '默认显示请求控制栏。')} /><Toggle checked={settings.autoScan} onChange={(value) => update('autoScan', value)} title={copy(language, 'Live scan', '实时扫描')} detail={copy(language, 'Update findings as content changes.', '内容变化时更新检测结果。')} /><Toggle checked={settings.blockCriticalSends} onChange={(value) => update('blockCriticalSends', value)} title={copy(language, 'Block critical raw sends', '阻止严重风险原文')} detail={copy(language, 'Only the redacted payload can proceed.', '仅脱敏版本可以继续。')} /><Toggle checked={settings.localHistoryEnabled} onChange={(value) => update('localHistoryEnabled', value)} title={copy(language, 'Local redacted history', '本地脱敏历史')} detail={copy(language, 'Save reviewed content only.', '只保存审查后的内容。')} /></div><label className="settings-textarea"><span>{copy(language, 'Custom sensitive terms', '自定义敏感词')}</span><textarea value={customTerms} onChange={(event) => setCustomTerms(event.target.value)} rows={5} placeholder={copy(language, 'One term per line', '每行一个敏感词')} /></label></section>
      <section><header><Icon name="git" /><div><h2>{copy(language, 'GitHub release channel', 'GitHub 发布通道')}</h2><p>{copy(language, 'The Updates page checks this public repository.', '版本更新页面会检查这个公开仓库。')}</p></div></header><div className="setting-fields"><label><span>Owner</span><input value={settings.githubOwner} onChange={(event) => update('githubOwner', event.target.value)} /></label><label><span>Repository</span><input value={settings.githubRepo} onChange={(event) => update('githubRepo', event.target.value)} /></label></div><Toggle checked={settings.autoCheckUpdates} onChange={(value) => update('autoCheckUpdates', value)} title={copy(language, 'Check updates on startup', '启动时检查更新')} detail={copy(language, 'Read the latest public GitHub Release metadata.', '读取最新公开 GitHub Release 元数据。')} /></section>
      <section className="danger-section"><header><Icon name="alert" /><div><h2>{copy(language, 'Local data controls', '本地数据控制')}</h2><p>{copy(language, 'Export or remove local records. Provider keys are stored separately in Keychain.', '导出或删除本地记录；Provider Key 单独保存在钥匙串。')}</p></div></header><div className="danger-actions-modern"><button onClick={downloadSettings}><Icon name="download" />{copy(language, 'Export settings', '导出设置')}</button><button onClick={() => { if (window.confirm(copy(language, 'Clear conversations?', '清空会话吗？'))) clearConversations(); }}><Icon name="trash" />{copy(language, 'Clear history', '清空历史')}</button><button onClick={() => { if (window.confirm(copy(language, 'Clear safety receipts?', '清空安全回执吗？'))) clearReceipts(); }}><Icon name="trash" />{copy(language, 'Clear receipts', '清空回执')}</button><button onClick={() => { if (window.confirm(copy(language, 'Clear token usage history?', '清空 Token 用量记录吗？'))) clearTokenUsage(); }}><Icon name="trash" />{copy(language, 'Clear token usage', '清空 Token 用量')}</button><button className="danger" onClick={() => void resetAll()}><Icon name="alert" />{copy(language, 'Reset application', '重置应用')}</button></div></section>
    </div>
  </main>;
}
