import type { PluginManifest } from "../agent-runtime/types";

export const BUILTIN_PLUGINS: PluginManifest[] = [
  {
    id: "obsidian-vault-writer",
    name: "Obsidian Vault Writer",
    version: "0.1.0",
    category: "knowledge",
    runtime: "node",
    description: "Read and write notes to a local Obsidian vault",
    permissions: ["file-read", "file-write"],
    riskLevel: "low",
    requiresApproval: true,
    entryPoint: "obsidian.ts",
    enabled: false,
    installed: false,
    installStatus: "none",
  },
  {
    id: "markdown-to-pdf",
    name: "Markdown to PDF",
    version: "0.1.0",
    category: "output",
    runtime: "node",
    description: "Convert Markdown output to PDF",
    permissions: ["file-write"],
    riskLevel: "low",
    requiresApproval: false,
    entryPoint: "output-pdf.ts",
    enabled: true,
    installed: true,
    installStatus: "installed",
  },
  {
    id: "markdown-to-docx",
    name: "Markdown to DOCX",
    version: "0.1.0",
    category: "output",
    runtime: "node",
    description: "Convert Markdown output to DOCX",
    permissions: ["file-write"],
    riskLevel: "low",
    requiresApproval: false,
    entryPoint: "output-docx.ts",
    enabled: true,
    installed: true,
    installStatus: "installed",
  },
  {
    id: "mindmap-generator",
    name: "Mind Map Generator",
    version: "0.1.0",
    category: "output",
    runtime: "node",
    description: "Generate mind maps from agent output using Mermaid or image models",
    permissions: ["network-out"],
    riskLevel: "low",
    requiresApproval: false,
    entryPoint: "mindmap.ts",
    enabled: true,
    installed: true,
    installStatus: "installed",
  },
  {
    id: "api-request-builder",
    name: "API Request Builder",
    version: "0.1.0",
    category: "api",
    runtime: "node",
    description: "Build and execute API requests to third-party services",
    permissions: ["network-out", "api-call"],
    riskLevel: "medium",
    requiresApproval: true,
    entryPoint: "api-connector.ts",
    enabled: false,
    installed: false,
    installStatus: "none",
  },
  {
    id: "knowledge-search",
    name: "Knowledge Search",
    version: "0.1.0",
    category: "knowledge",
    runtime: "node",
    description: "Search local knowledge bases and Obsidian vaults",
    permissions: ["file-read", "obsidian-read"],
    riskLevel: "low",
    requiresApproval: false,
    entryPoint: "knowledge-search.ts",
    enabled: false,
    installed: false,
    installStatus: "none",
  },
  {
    id: "mp4-import",
    name: "MP4 Import",
    version: "0.1.0",
    category: "media",
    runtime: "node",
    description: "Import MP4 files and extract frames for analysis",
    permissions: ["file-read", "media-ingest"],
    riskLevel: "medium",
    requiresApproval: true,
    entryPoint: "media-mp4.ts",
    enabled: false,
    installed: false,
    installStatus: "none",
  },
  {
    id: "audio-transcribe",
    name: "Audio Transcribe",
    version: "0.1.0",
    category: "media",
    runtime: "python",
    description: "Transcribe audio files using local or cloud models",
    permissions: ["file-read", "network-out"],
    riskLevel: "medium",
    requiresApproval: true,
    entryPoint: "audio-transcribe.ts",
    enabled: false,
    installed: false,
    installStatus: "none",
  },
  {
    id: "local-command-runner",
    name: "Local Command Runner",
    version: "0.1.0",
    category: "computer-use",
    runtime: "shell",
    description: "Execute approved local shell commands",
    permissions: ["shell-exec"],
    riskLevel: "high",
    requiresApproval: true,
    entryPoint: "local-command-runner.ts",
    enabled: false,
    installed: false,
    installStatus: "none",
  },
  {
    id: "computer-screenshot",
    name: "Computer Screenshot",
    version: "0.1.0",
    category: "computer-use",
    runtime: "binary",
    description: "Capture screenshots for visual context",
    permissions: ["screenshot"],
    riskLevel: "medium",
    requiresApproval: true,
    entryPoint: "screenshot.ts",
    enabled: false,
    installed: false,
    installStatus: "none",
  },
];

export function getBuiltinPlugins(): PluginManifest[] {
  return BUILTIN_PLUGINS;
}

export function getPluginsByCategory(category: string): PluginManifest[] {
  return BUILTIN_PLUGINS.filter((p) => p.category === category);
}

export function getPluginById(id: string): PluginManifest | undefined {
  return BUILTIN_PLUGINS.find((p) => p.id === id);
}