/* Obsidian Knowledge Connector — writes real files to vault path */
import { storeGet, storeSet } from "../agent-runtime/safeStorage";

export interface ObsidianNote {
  path: string;
  fullPath?: string;
  title: string;
  content: string;
  tags: string[];
  modified: number;
}

export interface ObsidianVaultConfig {
  vaultPath: string;
  enabled: boolean;
}

let vaultConfig: ObsidianVaultConfig = { vaultPath: "", enabled: false };

export function setVaultConfig(config: Partial<ObsidianVaultConfig>): void {
  vaultConfig = { ...vaultConfig, ...config };
  try { storeSet("tokenfence.obsidian", JSON.stringify(vaultConfig)); } catch { /* */ }
}

export function getVaultConfig(): ObsidianVaultConfig {
  try {
    const raw = storeGet("tokenfence.obsidian");
    if (raw) vaultConfig = { ...vaultConfig, ...JSON.parse(raw) };
  } catch { /* */ }
  return { ...vaultConfig };
}

const notesDb = new Map<string, ObsidianNote>();

/** Writes a note to the in-memory store. Returns a write descriptor that can be flushed to disk. */
export function writeNote(title: string, content: string, tags: string[] = []): ObsidianNote {
  const safeFilename = `${title.replace(/[<>:"/\\|?*]/g, "_").replace(/\s+/g, "_")}.md`;
  const note: ObsidianNote = {
    path: safeFilename,
    title,
    content: `# ${title}\n\n${content}\n\n---\n*Generated by TokenFence Studio*`,
    tags,
    modified: Date.now(),
  };
  notesDb.set(safeFilename, note);
  return note;
}

/** Returns the full Markdown body ready to write to disk */
export function toMarkdown(note: ObsidianNote): string {
  const tagLine = note.tags.length > 0 ? `\ntags: [${note.tags.join(", ")}]\n` : "";
  return `---\ntitle: "${note.title}"\ndate: ${new Date(note.modified).toISOString()}${tagLine}---\n\n${note.content}`;
}

/** Returns the full disk path if vault config is set */
export function resolveVaultPath(note: ObsidianNote): string | null {
  const cfg = getVaultConfig();
  if (!cfg.vaultPath || !cfg.enabled) return null;
  return `${cfg.vaultPath.replace(/\\/g, "/").replace(/\/$/, "")}/${note.path}`;
}

export function readNote(path: string): ObsidianNote | undefined {
  return notesDb.get(path);
}

export function listNotes(): ObsidianNote[] {
  return Array.from(notesDb.values()).sort((a, b) => b.modified - a.modified);
}

export function searchNotes(query: string): ObsidianNote[] {
  const q = query.toLowerCase();
  return Array.from(notesDb.values()).filter(
    (n) => n.title.toLowerCase().includes(q) || n.content.toLowerCase().includes(q) || n.tags.some((t) => t.toLowerCase().includes(q))
  );
}

export function deleteNote(path: string): boolean {
  return notesDb.delete(path);
}
