/* Output Plugin Generators — Real file generation */

export interface OutputResult {
  format: "pdf" | "docx" | "md" | "html" | "json";
  filename: string;
  content: string;
  isBase64?: boolean;   // true when content is base64-encoded binary
  filePath?: string;
  generatedAt: number;
}

export function generateMarkdown(content: string, title: string): OutputResult {
  const md = `# ${title}\n\n${content}\n\n---\n*Generated by TokenFence Studio*`;
  return { format: "md", filename: `${title.replace(/\s+/g, "_")}.md`, content: md, generatedAt: Date.now() };
}

export function generateHtml(content: string, title: string): OutputResult {
  const html = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>${title}</title><style>body{font-family:system-ui;max-width:800px;margin:40px auto;padding:0 20px;line-height:1.6;color:#1a1a2e}pre{background:#f4f4f5;padding:16px;border-radius:8px;overflow-x:auto}</style></head><body><h1>${title}</h1>${content}<hr><em>Generated by TokenFence Studio</em></body></html>`;
  return { format: "html", filename: `${title.replace(/\s+/g, "_")}.html`, content: html, generatedAt: Date.now() };
}

export function generateJson(data: unknown, title: string): OutputResult {
  const json = JSON.stringify(data, null, 2);
  return { format: "json", filename: `${title.replace(/\s+/g, "_")}.json`, content: json, generatedAt: Date.now() };
}

/* Minimal ZIP builder — creates valid ZIP archives with stored (uncompressed) entries */
function buildZip(files: { name: string; data: Uint8Array }[]): Uint8Array {
  const encoder = new TextEncoder();
  const localHeaders: Uint8Array[] = [];
  const centralHeaders: Uint8Array[] = [];
  let offset = 0;

  for (const file of files) {
    const nameBytes = encoder.encode(file.name);
    const crc = crc32(file.data);

    // Local file header
    const localHeader = new Uint8Array(30 + nameBytes.length + file.data.length);
    const lv = new DataView(localHeader.buffer);
    lv.setUint32(0, 0x04034b50, true);       // signature
    lv.setUint16(4, 20, true);                // version needed
    lv.setUint16(6, 0, true);                 // flags
    lv.setUint16(8, 0, true);                 // compression: stored
    lv.setUint16(10, 0, true);                // mod time
    lv.setUint16(12, 0, true);                // mod date
    lv.setUint32(14, crc, true);              // crc32
    lv.setUint32(18, file.data.length, true); // compressed size
    lv.setUint32(22, file.data.length, true); // uncompressed size
    lv.setUint16(26, nameBytes.length, true); // filename length
    lv.setUint16(28, 0, true);                // extra field length
    localHeader.set(nameBytes, 30);
    localHeader.set(file.data, 30 + nameBytes.length);
    localHeaders.push(localHeader);

    // Central directory header
    const centralHeader = new Uint8Array(46 + nameBytes.length);
    const cv = new DataView(centralHeader.buffer);
    cv.setUint32(0, 0x02014b50, true);
    cv.setUint16(4, 20, true);                // version made by
    cv.setUint16(6, 20, true);                // version needed
    cv.setUint16(8, 0, true);                 // flags
    cv.setUint16(10, 0, true);                // compression
    cv.setUint16(12, 0, true);                // mod time
    cv.setUint16(14, 0, true);                // mod date
    cv.setUint32(16, crc, true);
    cv.setUint32(20, file.data.length, true);
    cv.setUint32(24, file.data.length, true);
    cv.setUint16(28, nameBytes.length, true);
    cv.setUint16(30, 0, true);                // extra field length
    cv.setUint16(32, 0, true);                // comment length
    cv.setUint16(34, 0, true);                // disk number
    cv.setUint16(36, 0, true);                // internal attrs
    cv.setUint32(38, 0, true);                // external attrs
    cv.setUint32(42, offset, true);           // local header offset
    centralHeader.set(nameBytes, 46);
    centralHeaders.push(centralHeader);

    offset += localHeader.length;
  }

  // End of central directory
  const centralOffset = offset;
  const centralSize = centralHeaders.reduce((s, h) => s + h.length, 0);
  const eocd = new Uint8Array(22);
  const ev = new DataView(eocd.buffer);
  ev.setUint32(0, 0x06054b50, true);
  ev.setUint16(4, 0, true);                   // disk number
  ev.setUint16(6, 0, true);                   // central dir disk
  ev.setUint16(8, files.length, true);        // entries on disk
  ev.setUint16(10, files.length, true);       // total entries
  ev.setUint32(12, centralSize, true);        // central dir size
  ev.setUint32(16, centralOffset, true);      // central dir offset
  ev.setUint16(20, 0, true);                  // comment length

  // Concatenate everything
  const total = offset + centralSize + 22;
  const zip = new Uint8Array(total);
  let pos = 0;
  for (const h of localHeaders) { zip.set(h, pos); pos += h.length; }
  for (const h of centralHeaders) { zip.set(h, pos); pos += h.length; }
  zip.set(eocd, pos);
  return zip;
}

/* CRC32 implementation */
function crc32(data: Uint8Array): number {
  let crc = 0xFFFFFFFF;
  for (const byte of data) {
    crc ^= byte;
    for (let i = 0; i < 8; i++) {
      if (crc & 1) crc = (crc >>> 1) ^ 0xEDB88320;
      else crc >>>= 1;
    }
  }
  return (crc ^ 0xFFFFFFFF) >>> 0;
}

/* Real ZIP-wrapped DOCX generator */
export function generateDocx(content: string, title: string): OutputResult {
  const encoder = new TextEncoder();
  const safeTitle = title.replace(/[<>:"/\\|?*]/g, "_");

  const documentXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"
            xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <w:body>
    <w:p>
      <w:pPr><w:pStyle w:val="Title"/></w:pPr>
      <w:r><w:t>${escapeXml(title)}</w:t></w:r>
    </w:p>
    ${content.split("\n").map((line) => `<w:p><w:r><w:t>${escapeXml(line) || " "}</w:t></w:r></w:p>`).join("\n")}
    <w:p>
      <w:r><w:rPr><w:i/></w:rPr><w:t>Generated by TokenFence Studio</w:t></w:r>
    </w:p>
  </w:body>
</w:document>`;

  const relsXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>`;

  const docRelsXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"/>`;

  const contentTypesXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
</Types>`;

  const zip = buildZip([
    { name: "[Content_Types].xml", data: encoder.encode(contentTypesXml) },
    { name: "_rels/.rels", data: encoder.encode(relsXml) },
    { name: "word/document.xml", data: encoder.encode(documentXml) },
    { name: "word/_rels/document.xml.rels", data: encoder.encode(docRelsXml) },
  ]);

  // Encode as base64 for string transport
  const base64 = btoa(String.fromCharCode(...zip));
  return {
    format: "docx",
    filename: `${safeTitle}.docx`,
    content: base64,
    isBase64: true,
    generatedAt: Date.now(),
  };
}

function escapeXml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

export function generatePdf(content: string, title: string): OutputResult {
  const sanitized = content.replace(/[^\x20-\x7E\x0A\x0D\u00A0-\uFFFF]/g, "");
  const lines = sanitized.split("\n").slice(0, 40);
  const encoder = new TextEncoder();

  // Minimal valid PDF
  const streamContent = `BT\n/F1 10 Tf\n${lines.map((l, i) => {
    const escaped = l.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
    return `50 ${750 - i * 14} Td (${escaped.slice(0, 80)}) Tj`;
  }).join("\n")}\nET`;

  const pdf = `%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>
endobj
4 0 obj
<< /Length ${streamContent.length + 2} >>
stream
${streamContent}
endstream
endobj
5 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>
endobj
xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000266 00000 n 
00000${String(266 + streamContent.length + 20).padStart(10, "0")} 00000 n 
trailer
<< /Size 6 /Root 1 0 R >>
startxref
${266 + streamContent.length + 20 + 30}
%%EOF
`;

  return { format: "pdf", filename: `${title.replace(/\s+/g, "_")}.pdf`, content: pdf, generatedAt: Date.now() };
}

export function exportContent(content: string, title: string, format: OutputResult["format"]): OutputResult {
  switch (format) {
    case "md": return generateMarkdown(content, title);
    case "html": return generateHtml(content, title);
    case "json": return generateJson(content, title);
    case "pdf": return generatePdf(content, title);
    case "docx": return generateDocx(content, title);
  }
}

/** Write an OutputResult to disk, handling base64 decoding for binary formats */
export function outputToBytes(result: OutputResult): Uint8Array {
  if (result.isBase64) {
    const binary = atob(result.content);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
    return bytes;
  }
  return new TextEncoder().encode(result.content);
}
