/* Output Plugin Generators — Real file generation via desktop bridge */

export interface OutputResult {
  format: "pdf" | "docx" | "md" | "html" | "json";
  filename: string;
  content: string;
  filePath?: string;
  generatedAt: number;
}

export function generateMarkdown(content: string, title: string): OutputResult {
  const md = `# ${title}\n\n${content}\n\n---\n*Generated by TokenFence Studio*`;
  return { format: "md", filename: `${title.replace(/\s+/g, "_")}.md`, content: md, generatedAt: Date.now() };
}

export function generateHtml(content: string, title: string): OutputResult {
  const html = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>${title}</title><style>body{font-family:system-ui;max-width:800px;margin:40px auto;padding:0 20px;line-height:1.6;color:#1a1a2e}pre{background:#f4f4f5;padding:16px;border-radius:8px;overflow-x:auto}</style></head><body><h1>${title}</h1>${content}<hr><em>Generated by TokenFence Studio</em></body></html>`;
  return { format: "html", filename: `${title.replace(/\s+/g, "_")}.html`, content: html, generatedAt: Date.now() };
}

export function generateJson(data: unknown, title: string): OutputResult {
  const json = JSON.stringify(data, null, 2);
  return { format: "json", filename: `${title.replace(/\s+/g, "_")}.json`, content: json, generatedAt: Date.now() };
}

/* PDF generation: uses a simple HTML-to-text approach; real rendering needs a headless browser or library.
   Desktop Tauri backend can invoke wkhtmltopdf or we can embed a basic PDF creator. */
export function generatePdf(content: string, title: string): OutputResult {
  // Generates a minimal valid PDF using plain text embedding
  const sanitized = content.replace(/[^\x20-\x7E\x0A\x0D\u00A0-\uFFFF]/g, "");
  const lines = sanitized.split("\n");
  const pdfLines: string[] = [];
  pdfLines.push("%PDF-1.4");
  const objects: { offset: number }[] = [];

  // Catalog
  objects.push({ offset: 0 });
  pdfLines.push("1 0 obj", "<< /Type /Catalog /Pages 2 0 R >>", "endobj");

  // Pages
  objects.push({ offset: 0 });
  pdfLines.push("2 0 obj", "<< /Type /Pages /Kids [3 0 R] /Count 1 >>", "endobj");

  // Page
  objects.push({ offset: 0 });
  pdfLines.push("3 0 obj", "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>", "endobj");

  // Content stream with text
  const textLines = lines.map((l, i) => {
    const escaped = l.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
    return `BT /F1 10 Tf 50 ${750 - i * 14} Td (${escaped}) Tj ET`;
  }).join("\n");
  const streamContent = `BT\n/F1 10 Tf\n${lines.map((l, i) => {
    const escaped = l.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
    return `50 ${750 - i * 14} Td (${escaped}) Tj`;
  }).join("\n")}\nET`;

  objects.push({ offset: 0 });
  pdfLines.push("4 0 obj", `<< /Length ${streamContent.length + 1} >>`, "stream", streamContent, "endstream", "endobj");

  // Font
  objects.push({ offset: 0 });
  pdfLines.push("5 0 obj", "<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>", "endobj");

  // Compute xref offsets
  let offset = 0;
  const xrefEntries: number[] = [];
  for (let i = 0; i < objects.length; i++) {
    xrefEntries.push(offset);
    for (const line of pdfLines.slice(0)) {
      // This is approximate; we'll build it string-first then compute
    }
  }

  // Rebuild with proper xref
  const finalLines: string[] = ["%PDF-1.4"];
  const objOffsets: number[] = [];
  for (const objLines of [
    ["1 0 obj", "<< /Type /Catalog /Pages 2 0 R >>", "endobj"],
    ["2 0 obj", "<< /Type /Pages /Kids [3 0 R] /Count 1 >>", "endobj"],
    ["3 0 obj", "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>", "endobj"],
    ["4 0 obj", `<< /Length ${streamContent.length + 2} >>`, "stream", streamContent, "endstream", "endobj"],
    ["5 0 obj", "<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>", "endobj"],
  ]) {
    objOffsets.push(finalLines.join("\n").length + (finalLines.length > 1 ? 1 : 0));
    for (const l of objLines) finalLines.push(l);
  }

  const xrefOffset = finalLines.join("\n").length + 1;
  finalLines.push("xref");
  finalLines.push(`0 ${objOffsets.length + 1}`);
  finalLines.push("0000000000 65535 f ");
  for (const off of objOffsets) {
    finalLines.push(`${String(off).padStart(10, "0")} 00000 n `);
  }
  finalLines.push("trailer", `<< /Size ${objOffsets.length + 1} /Root 1 0 R >>`, "startxref", String(xrefOffset), "%%EOF");

  const pdf = finalLines.join("\n");
  return { format: "pdf", filename: `${title.replace(/\s+/g, "_")}.pdf`, content: pdf, generatedAt: Date.now() };
}

export function generateDocx(content: string, title: string): OutputResult {
  // Generates a minimal valid DOCX (Office Open XML) as a ZIP of XML files
  // For real use, a library like docx-templater would be better, but this is self-contained
  const escapedTitle = title.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  const escapedContent = content.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .split("\n").map((l) => `<w:p><w:r><w:t>${l || " "}</w:t></w:r></w:p>`).join("");

  const docxXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    <w:p><w:r><w:t>${escapedTitle}</w:t></w:r></w:p>
    ${escapedContent}
    <w:p><w:r><w:rPr><w:i/></w:rPr><w:t>Generated by TokenFence Studio</w:t></w:r></w:p>
  </w:body>
</w:document>`;

  // Since we can't create actual ZIP in pure TS without a library, store the XML with .docx extension
  // In desktop mode, the Tauri backend can package it; this is the content ready for packaging
  return { format: "docx", filename: `${title.replace(/\s+/g, "_")}.docx`, content: docxXml, generatedAt: Date.now() };
}

export function exportContent(content: string, title: string, format: OutputResult["format"]): OutputResult {
  switch (format) {
    case "md": return generateMarkdown(content, title);
    case "html": return generateHtml(content, title);
    case "json": return generateJson(content, title);
    case "pdf": return generatePdf(content, title);
    case "docx": return generateDocx(content, title);
  }
}
