/* Output Plugin Generators — MVP stub implementations */

export interface OutputResult {
  format: "pdf" | "docx" | "md" | "html" | "json";
  filename: string;
  content: string;
  blobUrl?: string;
  generatedAt: number;
}

export function generateMarkdown(content: string, title: string): OutputResult {
  const md = `# ${title}\n\n${content}\n\n---\n*Generated by TokenFence Studio*`;
  return { format: "md", filename: `${title.replace(/\s+/g, "_")}.md`, content: md, generatedAt: Date.now() };
}

export function generateHtml(content: string, title: string): OutputResult {
  const html = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>${title}</title><style>body{font-family:system-ui;max-width:800px;margin:40px auto;padding:0 20px;line-height:1.6;color:#1a1a2e}pre{background:#f4f4f5;padding:16px;border-radius:8px;overflow-x:auto}</style></head><body><h1>${title}</h1>${content}<hr><em>Generated by TokenFence Studio</em></body></html>`;
  return { format: "html", filename: `${title.replace(/\s+/g, "_")}.html`, content: html, generatedAt: Date.now() };
}

export function generateJson(data: unknown, title: string): OutputResult {
  const json = JSON.stringify(data, null, 2);
  return { format: "json", filename: `${title.replace(/\s+/g, "_")}.json`, content: json, generatedAt: Date.now() };
}

/* PDF and DOCX are stub generators — real conversion needs a server-side or local agent runtime */
export function generatePdf(markdown: string, title: string): OutputResult {
  return { format: "pdf", filename: `${title.replace(/\s+/g, "_")}.pdf`, content: markdown, generatedAt: Date.now() };
}

export function generateDocx(markdown: string, title: string): OutputResult {
  return { format: "docx", filename: `${title.replace(/\s+/g, "_")}.docx`, content: markdown, generatedAt: Date.now() };
}

export function exportContent(content: string, title: string, format: OutputResult["format"]): OutputResult {
  switch (format) {
    case "md": return generateMarkdown(content, title);
    case "html": return generateHtml(content, title);
    case "json": return generateJson(content, title);
    case "pdf": return generatePdf(content, title);
    case "docx": return generateDocx(content, title);
  }
}