import type { ProviderDefinition, ProviderId } from './types';

export const PROVIDERS: ProviderDefinition[] = [
  {
    id: 'local-demo', name: 'Local Sandbox', shortName: 'LOCAL', apiStyle: 'local-demo',
    defaultBaseUrl: 'local://tokenfence', defaultModel: 'tokenfence-safety-demo', modelSuggestions: ['tokenfence-safety-demo'],
    requiresCredential: false, accent: '#0f766e',
    capabilities: { vision: false, tools: false, reasoning: false, local: true, files: true },
    descriptionEn: 'Offline safety and UI demonstration. No provider request is sent.',
    descriptionZh: '离线演示安全流程与界面，不会向任何模型发送请求。',
  },
  {
    id: 'deepseek', name: 'DeepSeek', shortName: 'DS', apiStyle: 'openai-compatible',
    defaultBaseUrl: 'https://api.deepseek.com', defaultModel: 'deepseek-v4-flash',
    modelSuggestions: ['deepseek-v4-flash', 'deepseek-v4-pro', 'deepseek-chat', 'deepseek-reasoner'],
    requiresCredential: true, accent: '#3264c8',
    capabilities: { vision: false, tools: true, reasoning: true, local: false, files: true },
    descriptionEn: 'Fast coding, reasoning and general chat through the official API.',
    descriptionZh: '通过官方 API 提供编程、推理和通用对话。',
  },
  {
    id: 'openai', name: 'OpenAI', shortName: 'OA', apiStyle: 'openai-compatible',
    defaultBaseUrl: 'https://api.openai.com/v1', defaultModel: 'gpt-5.6',
    modelSuggestions: ['gpt-5.6', 'gpt-5.6-mini', 'gpt-5.5', 'gpt-4.1'],
    requiresCredential: true, accent: '#111827',
    capabilities: { vision: true, tools: true, reasoning: true, local: false, files: true },
    descriptionEn: 'General, multimodal and agent-capable OpenAI models.',
    descriptionZh: 'OpenAI 通用、多模态与 Agent 模型。',
  },
  {
    id: 'anthropic', name: 'Anthropic', shortName: 'AN', apiStyle: 'anthropic',
    defaultBaseUrl: 'https://api.anthropic.com/v1', defaultModel: 'claude-sonnet-4-5',
    modelSuggestions: ['claude-sonnet-4-5', 'claude-opus-4-1', 'claude-haiku-4-5'],
    requiresCredential: true, accent: '#b45309',
    capabilities: { vision: true, tools: true, reasoning: true, local: false, files: true },
    descriptionEn: 'Strong document reasoning and coding through the Messages API.',
    descriptionZh: '通过 Messages API 提供文档推理与编程能力。',
  },
  {
    id: 'gemini', name: 'Google Gemini', shortName: 'G', apiStyle: 'openai-compatible',
    defaultBaseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai', defaultModel: 'gemini-3.1-flash-lite',
    modelSuggestions: ['gemini-3.1-flash-lite', 'gemini-3.1-pro', 'gemini-3.5-flash'],
    requiresCredential: true, accent: '#5b5bd6',
    capabilities: { vision: true, tools: true, reasoning: true, local: false, files: true },
    descriptionEn: 'Multimodal processing and long-context document analysis.',
    descriptionZh: '多模态处理与长上下文文档分析。',
  },
  {
    id: 'qwen', name: 'Qwen', shortName: 'QW', apiStyle: 'openai-compatible',
    defaultBaseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1', defaultModel: 'qwen-plus',
    modelSuggestions: ['qwen-plus', 'qwen-max', 'qwen-turbo', 'qwen-vl-plus'],
    requiresCredential: true, accent: '#7c3aed',
    capabilities: { vision: true, tools: true, reasoning: true, local: false, files: true },
    descriptionEn: 'Chinese-first chat, document and vision workflows.',
    descriptionZh: '中文优先的对话、文档与视觉工作流。',
  },
  {
    id: 'kimi', name: 'Kimi / Moonshot', shortName: 'KM', apiStyle: 'openai-compatible',
    defaultBaseUrl: 'https://api.moonshot.cn/v1', defaultModel: 'moonshot-v1-32k',
    modelSuggestions: ['moonshot-v1-8k', 'moonshot-v1-32k', 'moonshot-v1-128k'],
    requiresCredential: true, accent: '#2563eb',
    capabilities: { vision: false, tools: true, reasoning: true, local: false, files: true },
    descriptionEn: 'Long-context Chinese document and research tasks.',
    descriptionZh: '适合中文长文档与研究任务。',
  },
  {
    id: 'doubao', name: 'Doubao / Ark', shortName: 'DB', apiStyle: 'openai-compatible',
    defaultBaseUrl: 'https://ark.cn-beijing.volces.com/api/v3', defaultModel: 'YOUR_ENDPOINT_ID',
    modelSuggestions: ['YOUR_ENDPOINT_ID'], requiresCredential: true, accent: '#0ea5e9',
    capabilities: { vision: true, tools: true, reasoning: true, local: false, files: true },
    descriptionEn: 'Volcengine Ark endpoint support. Use your endpoint ID as the model.',
    descriptionZh: '支持火山方舟，请将推理接入点 ID 填入模型字段。',
  },
  {
    id: 'zhipu', name: 'Zhipu GLM', shortName: 'GLM', apiStyle: 'openai-compatible',
    defaultBaseUrl: 'https://open.bigmodel.cn/api/paas/v4', defaultModel: 'glm-4-plus',
    modelSuggestions: ['glm-4-plus', 'glm-4-air', 'glm-4-flash', 'glm-4v-plus'],
    requiresCredential: true, accent: '#0f766e',
    capabilities: { vision: true, tools: true, reasoning: true, local: false, files: true },
    descriptionEn: 'GLM chat, vision and tool-capable models.',
    descriptionZh: '智谱 GLM 对话、视觉与工具调用模型。',
  },
  {
    id: 'openrouter', name: 'OpenRouter', shortName: 'OR', apiStyle: 'openai-compatible',
    defaultBaseUrl: 'https://openrouter.ai/api/v1', defaultModel: 'openrouter/auto',
    modelSuggestions: ['openrouter/auto'], requiresCredential: true, accent: '#7c2d12',
    capabilities: { vision: true, tools: true, reasoning: true, local: false, files: true },
    descriptionEn: 'Route across many hosted models from one API.',
    descriptionZh: '通过一个 API 路由到多种托管模型。',
  },
  {
    id: 'ollama', name: 'Ollama', shortName: 'OL', apiStyle: 'openai-compatible',
    defaultBaseUrl: 'http://127.0.0.1:11434/v1', defaultModel: 'qwen3',
    modelSuggestions: ['qwen3', 'llama3.3', 'deepseek-r1'], requiresCredential: false, accent: '#374151',
    capabilities: { vision: true, tools: true, reasoning: true, local: true, files: true },
    descriptionEn: 'Use locally installed Ollama models without an API key.',
    descriptionZh: '无需 API Key，使用本机 Ollama 模型。',
  },
  {
    id: 'lmstudio', name: 'LM Studio', shortName: 'LM', apiStyle: 'openai-compatible',
    defaultBaseUrl: 'http://127.0.0.1:1234/v1', defaultModel: 'local-model',
    modelSuggestions: ['local-model'], requiresCredential: false, accent: '#475569',
    capabilities: { vision: true, tools: true, reasoning: true, local: true, files: true },
    descriptionEn: 'Connect to the local OpenAI-compatible LM Studio server.',
    descriptionZh: '连接本机 LM Studio 的 OpenAI 兼容服务。',
  },
  {
    id: 'custom', name: 'Custom Compatible API', shortName: 'API', apiStyle: 'openai-compatible',
    defaultBaseUrl: 'https://example.com/v1', defaultModel: 'model-name',
    modelSuggestions: [], requiresCredential: true, accent: '#64748b',
    capabilities: { vision: false, tools: false, reasoning: false, local: false, files: true },
    descriptionEn: 'Any trusted OpenAI-compatible HTTPS endpoint.',
    descriptionZh: '任意可信的 OpenAI 兼容 HTTPS 接口。',
  },
];

export const PROVIDER_BY_ID = Object.fromEntries(PROVIDERS.map((provider) => [provider.id, provider])) as Record<ProviderId, ProviderDefinition>;

export function providerDefinition(id: ProviderId): ProviderDefinition {
  return PROVIDER_BY_ID[id] ?? PROVIDER_BY_ID.custom;
}
